[theme]
base = "light"
primaryColor = "#174C3C"
backgroundColor = "#F4F1E8"
secondaryBackgroundColor = "#EAE6DA"
textColor = "#202820"
font = "sans serif"

[server]
headless = true
enableCORS = true
enableXsrfProtection = true

[browser]
gatherUsageStats = false
